name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH secrets
        run: |
          echo "SSH User: ${{ secrets.SSH_USER }}"
          echo "Server IP: ${{ secrets.SERVER_IP }}"

      - name: Test git pull and restart commands
        run: |
          ssh -v -o ConnectTimeout=60 -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /opt/apps/Info_kiosk
            git pull origin main
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
          EOF
